var searchData=
[
  ['radarvisualizer',['RadarVisualizer',['../class_s_b_g_a_t___g_u_i_1_1_radar_visualizer.html#ae4ae11e8399f7600482b4cc216a20388',1,'SBGAT_GUI::RadarVisualizer']]],
  ['radarwindow',['RadarWindow',['../class_s_b_g_a_t___g_u_i_1_1_radar_window.html#aa4d7b86b3dfa674d000fda56de0cc6b1',1,'SBGAT_GUI::RadarWindow']]],
  ['rbegin',['rbegin',['../classnlohmann_1_1basic__json.html#a1ef93e2006dbe52667294f5ef38b0b10',1,'nlohmann::basic_json::rbegin() noexcept'],['../classnlohmann_1_1basic__json.html#a515e7618392317dbf4b72d3e18bf2ab2',1,'nlohmann::basic_json::rbegin() const noexcept']]],
  ['regularizecovariance',['RegularizeCovariance',['../class_s_b_g_a_t_filter_u_q.html#a47fbcac7d48b5df31f44b506c050e54f',1,'SBGATFilterUQ']]],
  ['reinterpret_5fbits',['reinterpret_bits',['../namespacenlohmann_1_1detail_1_1dtoa__impl.html#a1c5d30eb51e5e994a3f48bde104d2ce8',1,'nlohmann::detail::dtoa_impl']]],
  ['remove_5fprop',['remove_prop',['../class_s_b_g_a_t___g_u_i_1_1_mainwindow.html#af926008d86e47915910478ca869904fe',1,'SBGAT_GUI::Mainwindow']]],
  ['removeedge',['removeedge',['../class_adjacency___list.html#a472ebd0a5b83448088959d1173fba710',1,'Adjacency_List']]],
  ['removevertex',['removevertex',['../class_adjacency___list.html#a1794c310f08f59d85cb57b5d33caa667',1,'Adjacency_List']]],
  ['rend',['rend',['../classnlohmann_1_1basic__json.html#ac77aed0925d447744676725ab0b6d535',1,'nlohmann::basic_json::rend() noexcept'],['../classnlohmann_1_1basic__json.html#a4f73d4cee67ea328d785979c22af0ae1',1,'nlohmann::basic_json::rend() const noexcept']]],
  ['renderingpropertieswindow',['RenderingPropertiesWindow',['../class_s_b_g_a_t___g_u_i_1_1_rendering_properties_window.html#a1f36d5cf5b7aa5eded34f9073b3faa45',1,'SBGAT_GUI::RenderingPropertiesWindow']]],
  ['replace_5fsubstring',['replace_substring',['../classnlohmann_1_1json__pointer.html#aa7649d30da9fc10b0e20704a27aea2a9',1,'nlohmann::json_pointer']]],
  ['requestdata',['RequestData',['../class_s_b_g_a_t_filter.html#a2a2c7b46a94346c91fdf4405597b623b',1,'SBGATFilter::RequestData()'],['../class_s_b_g_a_t_mass_properties.html#a9c40a7bd836c36786fe95c80468ba927',1,'SBGATMassProperties::RequestData()'],['../class_s_b_g_a_t_obj_writer.html#af091e6db7ebe28b91cdf37e10ffed1f6',1,'SBGATObjWriter::RequestData()'],['../class_s_b_g_a_t_obs.html#a3be21065b1f1e854172ad8ca415d0798',1,'SBGATObs::RequestData()'],['../class_s_b_g_a_t_polyhedron_gravity_model.html#a0c662534046e3d4a8f44a87168496d33',1,'SBGATPolyhedronGravityModel::RequestData()'],['../class_s_b_g_a_t_shape_uncertainty.html#adaf010ba2272ffcce8b54d5f14dc01b5',1,'SBGATShapeUncertainty::RequestData()'],['../class_s_b_g_a_t_spherical_harmo.html#a91956684c577b8c98c80f7157274ec38',1,'SBGATSphericalHarmo::RequestData()'],['../class_s_b_g_a_t_srp_yorp.html#a464b0568fff83a305f635ddc02a0985e',1,'SBGATSrpYorp::RequestData()']]],
  ['reset',['reset',['../classnlohmann_1_1detail_1_1lexer.html#acba34bc18af19f93186e682d02c3942d',1,'nlohmann::detail::lexer']]],
  ['reverse_5fray_5ftrace',['reverse_ray_trace',['../class_s_b_g_a_t_obs_lightcurve.html#a22a06d6047bd2fb557cf2ce503f572f0',1,'SBGATObsLightcurve::reverse_ray_trace()'],['../class_s_b_g_a_t_obs_radar.html#a2f09dec6ce4754af08f32f65951dbbc2',1,'SBGATObsRadar::reverse_ray_trace()']]],
  ['rotate',['Rotate',['../class_s_b_g_a_t_transform_shape.html#a0ac355f135030eddc6361124681cbede',1,'SBGATTransformShape']]],
  ['runmcuqaccelerationinertial',['RunMCUQAccelerationInertial',['../class_s_b_g_a_t_polyhedron_gravity_model_u_q.html#a28221a488e45634b8c26581b3ffeb829',1,'SBGATPolyhedronGravityModelUQ::RunMCUQAccelerationInertial(std::string path_to_shape, const double &amp;density, const bool &amp;shape_in_meters, const bool &amp;hold_mass_constant, const arma::mat &amp;C_CC, const unsigned int &amp;N_samples, const std::vector&lt; arma::vec::fixed&lt; 3 &gt; &gt; &amp;all_positions, std::string output_dir, int N_saved_shapes, std::vector&lt; arma::vec &gt; &amp;deviations, std::vector&lt; double &gt; &amp;densities, std::vector&lt; std::vector&lt; arma::vec::fixed&lt; 3 &gt; &gt;&gt; &amp;all_accelerations)'],['../class_s_b_g_a_t_polyhedron_gravity_model_u_q.html#a6b3f60f62de24c427d200755feaa6fc6',1,'SBGATPolyhedronGravityModelUQ::RunMCUQAccelerationInertial(std::string path_to_shape, const double &amp;density, const bool &amp;shape_in_meters, const bool &amp;hold_mass_constant, const arma::mat &amp;C_CC, const unsigned int &amp;N_samples, const arma::vec::fixed&lt; 3 &gt; &amp;position, std::string output_dir, int N_saved_shapes, std::vector&lt; arma::vec &gt; &amp;deviations, std::vector&lt; double &gt; &amp;densities, std::vector&lt; arma::vec::fixed&lt; 3 &gt; &gt; &amp;accelerations)']]],
  ['runmcuqpotentialaccelerationinertial',['RunMCUQPotentialAccelerationInertial',['../class_s_b_g_a_t_polyhedron_gravity_model_u_q.html#a875c4d93795be4ba441c07d5117f993d',1,'SBGATPolyhedronGravityModelUQ::RunMCUQPotentialAccelerationInertial(std::string path_to_shape, const double &amp;density, const bool &amp;shape_in_meters, const bool &amp;hold_mass_constant, const arma::mat &amp;C_CC, const unsigned int &amp;N_samples, const std::vector&lt; arma::vec::fixed&lt; 3 &gt; &gt; &amp;all_positions, std::string output_dir, int N_saved_shapes, std::vector&lt; arma::vec &gt; &amp;deviations, std::vector&lt; double &gt; &amp;densities, std::vector&lt; std::vector&lt; arma::vec::fixed&lt; 3 &gt; &gt;&gt; &amp;all_accelerations, std::vector&lt; std::vector&lt; double &gt; &gt; &amp;all_potentials)'],['../class_s_b_g_a_t_polyhedron_gravity_model_u_q.html#aba17abe78f4bf42bfa3c18f9e77a5c84',1,'SBGATPolyhedronGravityModelUQ::RunMCUQPotentialAccelerationInertial(std::string path_to_shape, const double &amp;density, const bool &amp;shape_in_meters, const bool &amp;hold_mass_constant, const arma::mat &amp;C_CC, const unsigned int &amp;N_samples, const arma::vec::fixed&lt; 3 &gt; &amp;position, std::string output_dir, int N_saved_shapes, std::vector&lt; arma::vec &gt; &amp;deviations, std::vector&lt; double &gt; &amp;densities, std::vector&lt; arma::vec::fixed&lt; 3 &gt; &gt; &amp;accelerations, std::vector&lt; double &gt; &amp;potentials)']]],
  ['runmcuqslopes',['RunMCUQSlopes',['../class_s_b_g_a_t_polyhedron_gravity_model_u_q.html#af02823daca992a288152fd2c8eaea49f',1,'SBGATPolyhedronGravityModelUQ::RunMCUQSlopes(std::string path_to_shape, const double &amp;density, const arma::vec::fixed&lt; 3 &gt; &amp;Omega, const bool &amp;shape_in_meters, const bool &amp;hold_mass_constant, const arma::mat &amp;C_CC, const double &amp;period_standard_deviation, const unsigned int &amp;N_samples, const std::vector&lt; int &gt; &amp;all_facets, std::string output_dir, int N_saved_shapes, std::vector&lt; arma::vec &gt; &amp;deviations, std::vector&lt; double &gt; &amp;densities, std::vector&lt; double &gt; &amp;period_errors, std::vector&lt; std::vector&lt; double &gt; &gt; &amp;all_slopes)'],['../class_s_b_g_a_t_polyhedron_gravity_model_u_q.html#a523f12c575690fd03ad74f79c7a3ecd8',1,'SBGATPolyhedronGravityModelUQ::RunMCUQSlopes(std::string path_to_shape, const double &amp;density, const arma::vec::fixed&lt; 3 &gt; &amp;Omega, const bool &amp;shape_in_meters, const bool &amp;hold_mass_constant, const arma::mat &amp;C_CC, const double &amp;period_standard_deviation, const unsigned int &amp;N_samples, const int &amp;facet, std::string output_dir, int N_saved_shapes, std::vector&lt; arma::vec &gt; &amp;deviations, std::vector&lt; double &gt; &amp;densities, std::vector&lt; double &gt; &amp;period_errors, std::vector&lt; double &gt; &amp;slopes)']]],
  ['runmcuqvolumecominertia',['RunMCUQVolumeCOMInertia',['../class_s_b_g_a_t_mass_properties_u_q.html#af503d38846836308473ce6542d86c5c7',1,'SBGATMassPropertiesUQ']]]
];
